# Generated by Django 5.1.3 on 2024-11-26 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deliveryproduct',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='deliveryApp.delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='deliveryApp.product'),
        ),
        migrations.AddConstraint(
            model_name='deliveryproduct',
            constraint=models.UniqueConstraint(fields=('product_id', 'delivery_id'), name='unique_delivery_item'),
        ),
    ]
