# Generated by Django 5.1.3 on 2024-11-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0002_remove_delivery_product_alter_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryproduct',
            name='delivery',
            field=models.ForeignKey(blank=True, null=b'I00\n', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='deliveryApp.delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=b'I00\n', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='deliveryApp.product'),
        ),
    ]
