# Generated by Django 5.1.3 on 2024-11-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0004_alter_delivery_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='client_id',
            new_name='client',
        ),
    ]
